name: maple_story_book
description: "maple_story_book"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # http
  dio: 5.7.0

  # router
  go_router: 14.2.7

  # data
  json_annotation: 4.9.0
  freezed_annotation: 2.4.4

  # log
  logger: 2.4.0

  # state management
  bloc: 8.1.4
  flutter_bloc: 8.1.6

  # storage
  flutter_secure_storage: 9.2.2

  # permission
  permission_handler: 11.3.1

  # ui
  image_picker: 1.1.2
  google_fonts: 6.2.1
  cached_network_image: 3.4.1
  flutter_svg: 2.0.10+1
  fluttertoast: 8.2.8
  shimmer: 3.0.0
  flutter_screenutil: 5.9.3
  flutter_inappwebview: 6.0.0
  flutter_staggered_grid_view: 0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

  freezed: 2.5.7
  build_runner: 2.4.12
  json_serializable: 6.8.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
