name: bdh
description: "백동현 과제"
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.4.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  # http
  dio: ^5.7.0

  # storage
  get_storage: ^2.1.1

  # router
  go_router: ^14.2.7

  # state management
  flutter_bloc: ^8.1.6

  # annotation
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

  flutter_dotenv: ^5.1.0

  # UI
  google_fonts: ^6.2.1
  fluttertoast: ^8.2.8
  shimmer: ^3.0.0
  flutter_staggered_grid_view: ^0.7.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  freezed: ^2.5.2
  build_runner: ^2.4.10
  json_serializable: ^6.8.0


flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
